// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rnibfmfndfwtbtvsisaq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJuaWJmbWZuZGZ3dGJ0dnNpc2FxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4ODg3NDIsImV4cCI6MjA2MDQ2NDc0Mn0.m-lZ8eO8MVVs7fz_FcDEBVWa6r4tmTFabjJpNFDarzo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);